version: 3'
services:
  strapi:
    container_name: strapi
    command: yarn develop
    build: strapi
    environment:
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      NODE_ENV: development
    links:
      - postgres:postgres
    volumes:
      - ./strapi:/opt/app
    ports:
      - 1337:1337
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14.1
    container_name: postgres
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -h localhost
